print('This is an example of print function')
print('中文测试')
print("We're going to the store")
print('We\'re going to the store')
print('He said "Hi."')
print('Hi '+'there')
print('Hi '+'5')
print('Hi '+str(8))
print(int('8')+5)
print('Hi', 'hello')
print('100 + 200 =', 100 + 200)
name = input()
print(name)
